version: '3.7'
services:
  api:
    build:
        dockerfile: Dockerfile
        context: ./
    volumes:
      - ".:/app:cached"
    environment:
      - API_HOST=mountebank:3016
  mountebank:
    image: andyrbell/mountebank
    ports:
      - '2525:2525'
      - '3016:3016'
    command: 'mb start'